In [2]:
# !pip install numpy

In [3]:
import numpy as np

### np.array()

In [8]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim)

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
1


In [9]:
list2 = [[1, 2], [3, 4]]
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


### np.zeros()

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 3))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### np.ones()

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.full()

In [20]:
np.full(5, -2)

array([-2, -2, -2, -2, -2])

In [21]:
np.full((2, 3), -2)

array([[-2, -2, -2],
       [-2, -2, -2]])

### np.arange()

In [22]:
# np.array(range(start, stop, step))
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

### np.linspace()

In [26]:
# np.linspace(start, stop, num_of_elements_in_between)
np.linspace(1, 10, 2)

array([ 1., 10.])

In [28]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [30]:
np.linspace((1, 2), (5, 10), num=5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

### np.diag()

In [32]:
np.diag([2, 3, 4, 5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [33]:
np.diag([2, 3, 4, 5], k=1)

array([[0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0]])

In [34]:
np.diag([2, 3, 4, 5], k=-1)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0]])

### np.eye()

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### np.identity()

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random.rand()

In [38]:
np.random.rand(2, 3)

array([[0.03552366, 0.72270394, 0.50242175],
       [0.02601431, 0.03019506, 0.56974503]])

In [39]:
np.random.rand(2, 3)

array([[0.40354588, 0.43629993, 0.85050883],
       [0.34668425, 0.55891344, 0.23523634]])

### np.random.randint()

In [47]:
np.random.randint(2, 7, size=(3, 7))

array([[2, 2, 3, 5, 5, 3, 3],
       [4, 2, 3, 6, 5, 4, 6],
       [2, 2, 3, 5, 2, 6, 3]])