In [1]:
import numpy as np

In [2]:
shape = (2, 3)  # Shape of the weight matrix for a given layer

def initialize_zeros(shape):   # Zero Initialization
    return np.zeros(shape)

def initialize_random(shape):  # Random Initialization
    return np.random.randn(*shape)

def initialize_xavier(shape):  # Xavier Initialization
    fan_in, fan_out = shape[0], shape[1]
    variance = np.sqrt(2.0 / (fan_in + fan_out))
    return np.random.randn(*shape) * variance

def initialize_he(shape):  # He Initialization
    fan_in = shape[0]
    variance = np.sqrt(2.0 / fan_in)
    return np.random.randn(*shape) * variance

def initialize_lecun(shape):  # LeCun Initialization
    fan_in = shape[0]
    variance = np.sqrt(1.0 / fan_in)
    return np.random.randn(*shape) * variance

In [3]:
print("Zero Initialization: \n", initialize_zeros(shape))
print("\nRandom Initialization: \n", initialize_random(shape))
print("\nXavier Initialization: \n", initialize_xavier(shape))
print("\nHe Initialization: \n", initialize_he(shape))
print("\nLeCun Initialization: \n", initialize_lecun(shape))

Zero Initialization: 
 [[0. 0. 0.]
 [0. 0. 0.]]

Random Initialization: 
 [[-1.06694058 -0.3983499   1.22605166]
 [ 0.24026662 -0.46008179  0.98224231]]

Xavier Initialization: 
 [[ 0.7190972   0.91142296  0.18613198]
 [-0.90302658  0.67083746  1.15611127]]

He Initialization: 
 [[ 1.39796339  1.47547315 -0.65862243]
 [-1.08449309  1.09134882 -0.39529776]]

LeCun Initialization: 
 [[ 0.57373496  1.22710942  0.15930771]
 [-0.65063071  0.73440679 -0.67024218]]
