In [1]:
import numpy as np

In [2]:
def dropout_forward(X, dropout_rate):
    mask = np.random.rand(*X.shape) < (1 - dropout_rate)
    out = X * mask / (1 - dropout_rate)
    cache = (mask, dropout_rate)
    return out, cache

def dropout_backward(dout, cache):
    mask, dropout_rate = cache
    dX = dout * mask / (1 - dropout_rate)
    return dX

In [3]:
# Forward pass with dropout
dropout_rate = 0.2
X = np.random.randn(4, 5)  # Example hidden layer output
out, cache = dropout_forward(X, dropout_rate)

In [4]:
# Backward pass with dropout
dout = np.random.randn(*out.shape)  # Example gradient from subsequent layer
dX = dropout_backward(dout, cache)

In [5]:
print("Original X:\n", X)
print("\nOutput with dropout:\n", out)
print("\nGradient after dropout:\n", dX)

Original X:
 [[-0.08519593 -0.29491034  2.57357226  0.87073336  1.91084363]
 [ 1.6085391  -0.37490219 -0.84316962  0.08543693  1.2801493 ]
 [-0.51743279 -1.59138133  0.71590046  0.75913856  0.9847605 ]
 [ 0.01060837 -1.24200521  0.18092982  0.70046806 -0.89608493]]

Output with dropout:
 [[-0.10649491 -0.36863793  3.21696533  1.0884167   2.38855454]
 [ 0.         -0.46862774 -1.05396202  0.10679617  1.60018663]
 [-0.64679099 -1.98922666  0.89487557  0.          1.23095062]
 [ 0.         -1.55250651  0.22616228  0.87558507 -1.12010616]]

Gradient after dropout:
 [[-0.59372041  1.07096313  1.06882634  1.78229544  1.01449467]
 [-0.         -2.30641661 -0.23643777  2.49407385 -1.8077579 ]
 [ 0.66981557  3.29107534  0.40651687  0.          0.51503122]
 [ 0.         -0.35714271  0.2129555   0.68592714  1.32336732]]
