In [1]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1.0, 2.0, 3.0], dtype=np.float64)
c = np.array([True, False, True], dtype=np.bool_)

print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
bool


In [2]:
d = np.array([1, 2, 3], dtype=np.float64)
d

array([1., 2., 3.])

In [3]:
e = np.array([1.0, 2.0, 3.0], dtype=np.int32)
e

array([1, 2, 3], dtype=int32)

In [5]:
f = np.array([True, False, True], dtype=np.int32)
f

array([1, 0, 1], dtype=int32)

In [6]:
a.dtype

dtype('int32')

In [9]:
g = a.astype(np.float32)

In [10]:
g

array([1., 2., 3.], dtype=float32)