In [1]:
import numpy as np

## Elementwise Operations

In [3]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [9, 8,7 ]])

In [4]:
a

array([[4, 5, 6],
       [5, 7, 9]])

In [5]:
b

array([[1, 2, 3],
       [9, 8, 7]])

In [6]:
a + b

array([[ 5,  7,  9],
       [14, 15, 16]])

In [7]:
a - b

array([[ 3,  3,  3],
       [-4, -1,  2]])

## Matrix operations

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
b

array([[5, 6],
       [7, 8]])

In [9]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [12]:
c = np.array([[1, 2, 3], [3, 4, 5]])
d = np.array([[5, 6], [7, 8]])

In [13]:
np.dot(c, d)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [14]:
np.dot(d, c)

array([[23, 34, 45],
       [31, 46, 61]])

In [15]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [16]:
np.trace(a)

5

In [17]:
np.linalg.det(a)

-2.0000000000000004

In [19]:
d = np.random.rand(2, 3)

In [20]:
d.shape

(2, 3)

In [21]:
np.linalg.det(d)

LinAlgError: Last 2 dimensions of the array must be square

In [22]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [24]:
a = [[1, 2], [3, 5]]
b = [1, 2]

In [25]:
np.linalg.solve(a, b)

array([-1.,  1.])

## Broadcasting

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [28]:
b

array([10, 20])

In [29]:
a + b

array([[11, 22],
       [13, 24]])

## Why numpy over python's for loop

In [36]:
import numpy as np
import time

# Using NumPy for element-wise multiplication
a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
c = a * b
end = time.time()
numpy_execution_time = end - start
print("Time taken by NumPy: {:.6f} seconds".format(numpy_execution_time))

# Using Python for loop for element-wise multiplication
a = list(a)
b = list(b)
c = []

start = time.time()
for i in range(len(a)):
    c.append(a[i] * b[i])
end = time.time()
for_loop_execution_time = end - start
print("Time taken by Python for loop: {:.6f} seconds".format(end - start))

print(f'Numpy is {int(for_loop_execution_time/numpy_execution_time)} times faster than Python for loop!')

Time taken by NumPy: 0.023041 seconds
Time taken by Python for loop: 0.264053 seconds
Numpy is 11 times faster than Python for loop!


In [31]:
68*68

4624

In [32]:
4624/60

77.06666666666666

In [33]:
77/24

3.2083333333333335