In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4], [5, 6]])
mask = np.array([True, False, True])

In [3]:
b = a[mask]

print(b)

[[1 2]
 [5 6]]


In [4]:
mask = np.array([[True, False], [True, True], [True, False]])

In [5]:
a[mask]

array([1, 3, 4, 5])

In [6]:
mask = np.array([[True, False], True, [True, False]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [7]:
mask = np.array([[True, False], False, [True, False]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])
mask = (a > 2)

In [9]:
a[mask]

array([3, 4, 5, 6])