In [4]:
import numpy as np

In [1]:
import numpy as np

class MLP:
    def __init__(self, input_size, hidden_sizes, output_size, activation='sigmoid'):
        self.input_size = input_size
        self.hidden_sizes = hidden_sizes
        self.output_size = output_size

        self.weights = []
        self.biases = []

        layer_sizes = [input_size] + hidden_sizes + [output_size]

        for i in range(len(layer_sizes) - 1):
            weight_matrix = np.random.randn(layer_sizes[i], layer_sizes[i+1])
            self.weights.append(weight_matrix)
            bias_vector = np.zeros(layer_sizes[i+1])
            self.biases.append(bias_vector)

        if activation == 'sigmoid':
            self.activation_function = self._sigmoid
        elif activation == 'tanh':
            self.activation_function = self._tanh
        elif activation == 'relu':
            self.activation_function = self._relu
        else:
            raise ValueError("Unsupported activation function.")

    def forward(self, x):
        activations = [x]

        for i in range(len(self.weights)):
            linear_output = np.dot(activations[-1], self.weights[i]) + self.biases[i]
            output = self.activation_function(linear_output)
            activations.append(output)

        return activations[-1]

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def _tanh(self, x):
        return np.tanh(x)

    def _relu(self, x):
        return np.maximum(0, x)

In [2]:
# Example usage
mlp = MLP(input_size=4, hidden_sizes=[8, 6], output_size=3, activation='sigmoid')
input_data = np.random.randn(10, 4)  # Example input data with 10 samples
output = mlp.forward(input_data)  # Compute the MLP's output
print(output)

[[0.92272509 0.49322623 0.53519398]
 [0.95437191 0.47376639 0.48055043]
 [0.86940995 0.53931277 0.43747962]
 [0.98464751 0.65293492 0.36614747]
 [0.98595298 0.58175658 0.3344579 ]
 [0.94248822 0.53046467 0.37941046]
 [0.9874768  0.56921626 0.38081922]
 [0.87952992 0.55070984 0.43182991]
 [0.93794668 0.50832479 0.53023818]
 [0.95986012 0.43079935 0.50889527]]
