1D Array: `array_name[start:stop:step]` (Similar to Python list)

2D Array: `array_name[row_idx, col_idx]` (Similar to Matrix)

ND Array: `array_name[dim1_idx, dim2_idx, ..., dimN_idx]`

In [1]:
import numpy as np

## One Dimensional Array

In [2]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
list1[1:7:2]

[2, 4, 6]

In [4]:
array1 = np.array(list1)

In [5]:
array1[1:7:2]

array([2, 4, 6])

## Multi Dimensional

In [6]:
list2 = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7, 9, 11, 13, 15]]

In [7]:
list2[0][5:]

[6, 7, 8]

In [8]:
array2 = np.array(list2)

In [9]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [10]:
array2[0][5:]

array([6, 7, 8])

In [11]:
array2[0, 5:]

array([6, 7, 8])

In [12]:
array2[:, 1:4]

array([[2, 3, 4],
       [3, 5, 7]])

In [13]:
# [start : stop : step]
array2[:, 1::2]

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])

In [14]:
list3 = [[1, 2, 3, 4, 5, 6, 7, 8], [1, 3, 5, 7, 9, 11, 13, 15], [15, 25, 9999, 376, 19, 420, 786, 555]]

In [15]:
array3 = np.array(list3)

In [16]:
array3

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  15,   25, 9999,  376,   19,  420,  786,  555]])

In [17]:
array3[1:, 4:7]

array([[  9,  11,  13],
       [ 19, 420, 786]])

In [20]:
array3.shape

(3, 8)

In [23]:
array3.shape[0]

3

In [26]:
list4 = [
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[1, 3, 5, 7], [9, 11, 13, 15]],
    [[15, 25, 9999, 376], [19, 420, 786, 555]]
]

In [27]:
array4 = np.array(list4)

In [28]:
array4.shape

(3, 2, 4)

In [29]:
array4.ndim

3

In [31]:
array4[:2, :, 1:3]

array([[[ 2,  3],
        [ 6,  7]],

       [[ 3,  5],
        [11, 13]]])