In [1]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
a.ndim

2

In [8]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [9]:
a.sum()

21

In [13]:
a.max(axis=1)

array([3, 6])

In [14]:
a.argmax(axis=1)

array([2, 2])

In [15]:
a.shape

(2, 3)

In [17]:
# NOTE: Product of elements should be conserved
a.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
b = a.reshape((1, 2, 3))

In [21]:
b.shape

(1, 2, 3)

In [23]:
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])

In [32]:
np.concatenate((m, n), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.concatenate((m, n), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
np.concatenate((m, n), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [33]:
string = 'hello how are you'

In [34]:
string.split(' ')

['hello', 'how', 'are', 'you']

In [35]:
a = a.reshape(6)

In [36]:
a

array([1, 2, 3, 4, 5, 6])

In [37]:
np.split(a, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [38]:
np.split(a, [2, 5, 7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int64)]